---
title: "GOM-series sea surface temperature"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
source("setup.R")
```

### OISST monthly means

We downloaded monthly mean SST data from [OISST](https://psl.noaa.gov/data/gridded/data.noaa.oisst.v2.highres.html).  For each region we computed the mean pixel value at each month.

> Note that we store the OISST data for by date for each subregion.  This file can be updated as needed using `fetch_oisst()` - see below.

```{r, message = FALSE}
x <- read_oisst() |> 
  dplyr::mutate(month = factor(format(date, "%b"), levels = month.abb)) |>
  dplyr::group_by(region) |>
  glimpse()
```

```{r, message = FALSE}
ggplot(data = x, aes(x = date, y = mean)) +
  geom_line() + 
  labs(y = "Mean SST") + 
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~ region)
```

```{r, message = FALSE}
georges_basin = dplyr::filter(x, region == 'Georges Basin')
ggplot(data = georges_basin, aes(x = date, y = min)) +
  labs(y = "Min and Max SST") + 
  geom_line() + 
  geom_smooth(method = "lm", se = FALSE) +
  geom_line(aes(x = date, y = max)) + 
  geom_smooth(aes(x = date, y = max), method = "lm", se = FALSE, color = "orange") +
  facet_wrap(~ month)
```


### Updating the local dataset

It's easy to build or renew the local dataset.

```
r <- fetch_oisst()
```