suppressPackageStartupMessages({
  here::i_am("setup.R")
  library(rlang)
  library(httr)
  library(here)
  library(R6)
  library(xml2)
  library(rerddap)
  library(sf)
  library(stars)
  library(rnaturalearth)
  library(copernicus)
  library(stsaav)
  library(wdspaleo)
  library(ghcnd)
  library(ncdf4)
  library(ggplot2)
  library(scales)
  library(tidyr)
  library(readr)
  library(dplyr)
  library(dataRetrieval)
  library(stringr)
})

PATH = here::here()
# source functionality
for (f in list.files(here("functions"), pattern = "^.*\\.R$", full.names = TRUE)){
  source(f)
}
