---
title: "Surprise"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning = FALSE, message = FALSE}
source("../setup.R")
```


# A toy example.

Read in the export data, but select just a few columns of interest and filter to recent times.

```{r}
x = read_export(by = 'year', 
                selection = read_target_vars(treatment = c("median")),
                replace_names = TRUE, 
                standardize = FALSE) |>
  dplyr::filter(date >= as.Date("1950-01-01")) |>
  dplyr::select(date, dplyr::contains(c("nao", "amo", "gsi"))) 

plot_export(x)
```



Plot without binning into surprise categories.

```{r}
win = 10
s = surprise(x, win = win) |>
  dplyr::filter(date >= as.Date("1980-01-01"))

plot_surprise(s, surprise = NULL, title = NULL)
```

And plot again but this time as categorical "-surprise", "no surprise", "surprise" groups.

```{r}
plot_surprise(s, surprise = 2, title = NULL)
```



Now run again with the target variables using `median`, `q25` and `q75`.


```{r}
med_st = read_export(by = 'year', 
                standardize = TRUE, 
                selection = read_target_vars(treatment = "median")) |>
  dplyr::filter(date >= as.Date("1970-01-01")) |>
  replace_var_names()
g1 = plot_export(med_st, title = "Standardized Median by Year")

med_sup = read_export(by = 'year', 
                standardize = FALSE, 
                selection = read_target_vars(treatment = "median")) |>
  dplyr::filter(date >= as.Date("1970-01-01")) |>
  replace_var_names()
g2 = plot_surprise(surprise(med_sup, win = 20), surprise = 2, title = "Median Surprise by Year")

print(g1/g2)
```
```{r}
q25 = read_export(by = 'year', 
                standardize = TRUE, 
                selection = read_target_vars(treatment = "q25")) |>
  dplyr::filter(date >= as.Date("1970-01-01")) |>
  replace_var_names()
g1 = plot_export(q25, title = "Standardized Q25 by Year")

q25 = read_export(by = 'year', 
                standardize = FALSE, 
                selection = read_target_vars(treatment = "q25")) |>
  dplyr::filter(date >= as.Date("1970-01-01")) |>
  replace_var_names()
g2 = plot_surprise(surprise(q25, win = 20), surprise = 2, title = "Q25 Surprise by Year")

print(g1/g2)
```


```{r}
q75 = read_export(by = 'year', 
                standardize = TRUE, 
                selection = read_target_vars(treatment = "q75")) |>
  dplyr::filter(date >= as.Date("1970-01-01")) |>
  replace_var_names()
g1 = plot_export(q75, title = "Standardized Q75 by Year")

q75 = read_export(by = 'year', 
                standardize = FALSE, 
                selection = read_target_vars(treatment = "q75")) |>
  dplyr::filter(date >= as.Date("1970-01-01")) |>
  replace_var_names()
g2 = plot_surprise(surprise(q75, win = 20), surprise = 2, title = "Q75 Surprise by Year")

print(g1/g2)
```